"""add mail verification

Revision ID: f2f38fdf5985
Revises: 6aa0a9cc6af7
Create Date: 2025-05-15 09:20:39.812971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f2f38fdf5985'
down_revision: Union[str, None] = '6aa0a9cc6af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('group_invites_group_id_fkey', 'group_invites', type_='foreignkey')
    op.create_foreign_key(None, 'group_invites', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('email_verification_token', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_token')
    op.drop_column('users', 'email_verified')
    op.drop_constraint(None, 'group_invites', type_='foreignkey')
    op.create_foreign_key('group_invites_group_id_fkey', 'group_invites', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
