// This file is auto-generated by @hey-api/openapi-ts

export type Balance = {
    user_id: string;
    group_id?: string | null;
    total_balance: number;
    total_owed_to_others: number;
    total_owed_by_others: number;
    user_balances: Array<UserBalance>;
};

export type BodyLoginAuthLoginPost = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type CreateGroup = {
    name: string;
};

export type EmailConfirmationRequest = {
    frontend_url: string;
    token: number;
};

export type Group = {
    id?: string;
    created_at?: string;
    updated_at?: string;
    name: string;
};

export type GroupExpandedResponse = {
    id: string;
    name: string;
    created_at: string;
    updated_at: string;
    users?: Array<UserResponse>;
    invites?: Array<GroupInviteResponse> | null;
    balance?: Balance | null;
    transactions?: Array<TransactionRead> | null;
};

export type GroupInviteCreate = {
    email?: string | null;
};

export type GroupInviteResponse = {
    id: string;
    email?: string | null;
    group_id: string;
    token: string;
    created_at: string;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type InvitationTokenResponse = {
    token: string;
};

export type Token = {
    access_token: string;
    token_type: string;
};

export type TransactionCreate = {
    id?: string;
    created_at?: string;
    updated_at?: string;
    /**
     * Total amount in smallest currency unit (e.g., cents)
     */
    amount: number;
    title: string;
    purchased_on?: string;
    transaction_type?: TransactionType;
    group_id: string;
    payer_id: string;
    participants: Array<TransactionParticipantCreate>;
};

export type TransactionParticipantCreate = {
    amount_owed: number;
    debtor_id: string;
};

export type TransactionParticipantRead = {
    amount_owed: number;
    transaction_id: string;
    debtor_id: string;
    id: string;
    created_at: string;
    updated_at: string;
    debtor: User;
};

export type TransactionRead = {
    id?: string;
    created_at?: string;
    updated_at?: string;
    /**
     * Total amount in smallest currency unit (e.g., cents)
     */
    amount: number;
    title: string;
    purchased_on?: string;
    transaction_type?: TransactionType;
    group_id: string;
    payer_id: string;
    participants: Array<TransactionParticipantRead>;
    payer: User;
    group: Group;
};

export type TransactionType = 'EVEN' | 'AMOUNT' | 'PERCENTAGE';

export type TransactionUpdate = {
    amount?: number | null;
    title?: string | null;
    purchased_on?: string | null;
    transaction_type?: TransactionType | null;
    payer_id?: string | null;
};

export type UpdateGroup = {
    name?: string;
};

export type User = {
    id?: string;
    created_at?: string;
    updated_at?: string;
    username: string;
    email: string;
    email_verified?: boolean;
    email_verification_token?: number;
    password: string;
};

export type UserBalance = {
    user: UserResponse;
    balance: number;
};

export type UserCreate = {
    email: string;
    password: string;
    username: string;
};

export type UserInfoUpdate = {
    username: string;
};

export type UserResponse = {
    id: string;
    email: string;
    username: string;
    email_verified: boolean;
    created_at: string;
    updated_at: string;
};

export type UserUpdatePassword = {
    old_password: string;
    new_password: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type DeleteUserAccountDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/';
};

export type DeleteUserAccountDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserAccountDeleteResponse = DeleteUserAccountDeleteResponses[keyof DeleteUserAccountDeleteResponses];

export type ReadUsersMeAccountGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/';
};

export type ReadUsersMeAccountGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type ReadUsersMeAccountGetResponse = ReadUsersMeAccountGetResponses[keyof ReadUsersMeAccountGetResponses];

export type UpdateUserInfoAccountPutData = {
    body: UserInfoUpdate;
    path?: never;
    query?: never;
    url: '/account/';
};

export type UpdateUserInfoAccountPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserInfoAccountPutError = UpdateUserInfoAccountPutErrors[keyof UpdateUserInfoAccountPutErrors];

export type UpdateUserInfoAccountPutResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UpdateUserInfoAccountPutResponse = UpdateUserInfoAccountPutResponses[keyof UpdateUserInfoAccountPutResponses];

export type UpdatePasswordAccountPasswordPutData = {
    body: UserUpdatePassword;
    path?: never;
    query?: never;
    url: '/account/password';
};

export type UpdatePasswordAccountPasswordPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePasswordAccountPasswordPutError = UpdatePasswordAccountPasswordPutErrors[keyof UpdatePasswordAccountPasswordPutErrors];

export type UpdatePasswordAccountPasswordPutResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UpdatePasswordAccountPasswordPutResponse = UpdatePasswordAccountPasswordPutResponses[keyof UpdatePasswordAccountPasswordPutResponses];

export type RegisterAuthRegisterPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterAuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterAuthRegisterPostError = RegisterAuthRegisterPostErrors[keyof RegisterAuthRegisterPostErrors];

export type RegisterAuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: UserResponse;
};

export type RegisterAuthRegisterPostResponse = RegisterAuthRegisterPostResponses[keyof RegisterAuthRegisterPostResponses];

export type LoginAuthLoginPostData = {
    body: BodyLoginAuthLoginPost;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAuthLoginPostError = LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginAuthLoginPostResponse = LoginAuthLoginPostResponses[keyof LoginAuthLoginPostResponses];

export type ConfirmEmailAuthConfirmEmailPostData = {
    body: EmailConfirmationRequest;
    path?: never;
    query?: never;
    url: '/auth/confirm-email';
};

export type ConfirmEmailAuthConfirmEmailPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConfirmEmailAuthConfirmEmailPostError = ConfirmEmailAuthConfirmEmailPostErrors[keyof ConfirmEmailAuthConfirmEmailPostErrors];

export type ConfirmEmailAuthConfirmEmailPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type ConfirmEmailAuthConfirmEmailPostResponse = ConfirmEmailAuthConfirmEmailPostResponses[keyof ConfirmEmailAuthConfirmEmailPostResponses];

export type GetUserBalancesBalancesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/balances/';
};

export type GetUserBalancesBalancesGetResponses = {
    /**
     * Successful Response
     */
    200: Balance;
};

export type GetUserBalancesBalancesGetResponse = GetUserBalancesBalancesGetResponses[keyof GetUserBalancesBalancesGetResponses];

export type ReadGroupsGroupsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/groups/';
};

export type ReadGroupsGroupsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<Group>;
};

export type ReadGroupsGroupsGetResponse = ReadGroupsGroupsGetResponses[keyof ReadGroupsGroupsGetResponses];

export type CreateGroupGroupsPostData = {
    body: CreateGroup;
    path?: never;
    query?: never;
    url: '/groups/';
};

export type CreateGroupGroupsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateGroupGroupsPostError = CreateGroupGroupsPostErrors[keyof CreateGroupGroupsPostErrors];

export type CreateGroupGroupsPostResponses = {
    /**
     * Successful Response
     */
    201: Group;
};

export type CreateGroupGroupsPostResponse = CreateGroupGroupsPostResponses[keyof CreateGroupGroupsPostResponses];

export type DeleteGroupGroupsGroupIdDeleteData = {
    body?: never;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/groups/{group_id}';
};

export type DeleteGroupGroupsGroupIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteGroupGroupsGroupIdDeleteError = DeleteGroupGroupsGroupIdDeleteErrors[keyof DeleteGroupGroupsGroupIdDeleteErrors];

export type DeleteGroupGroupsGroupIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteGroupGroupsGroupIdDeleteResponse = DeleteGroupGroupsGroupIdDeleteResponses[keyof DeleteGroupGroupsGroupIdDeleteResponses];

export type ReadGroupGroupsGroupIdGetData = {
    body?: never;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/groups/{group_id}';
};

export type ReadGroupGroupsGroupIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadGroupGroupsGroupIdGetError = ReadGroupGroupsGroupIdGetErrors[keyof ReadGroupGroupsGroupIdGetErrors];

export type ReadGroupGroupsGroupIdGetResponses = {
    /**
     * Successful Response
     */
    200: GroupExpandedResponse;
};

export type ReadGroupGroupsGroupIdGetResponse = ReadGroupGroupsGroupIdGetResponses[keyof ReadGroupGroupsGroupIdGetResponses];

export type UpdateGroupGroupsGroupIdPutData = {
    body: UpdateGroup;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/groups/{group_id}';
};

export type UpdateGroupGroupsGroupIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateGroupGroupsGroupIdPutError = UpdateGroupGroupsGroupIdPutErrors[keyof UpdateGroupGroupsGroupIdPutErrors];

export type UpdateGroupGroupsGroupIdPutResponses = {
    /**
     * Successful Response
     */
    200: Group;
};

export type UpdateGroupGroupsGroupIdPutResponse = UpdateGroupGroupsGroupIdPutResponses[keyof UpdateGroupGroupsGroupIdPutResponses];

export type ReadGroupTransactionsGroupsGroupIdTransactionsGetData = {
    body?: never;
    path: {
        group_id: string;
    };
    query?: {
        skip?: number;
        limit?: number;
    };
    url: '/groups/{group_id}/transactions';
};

export type ReadGroupTransactionsGroupsGroupIdTransactionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadGroupTransactionsGroupsGroupIdTransactionsGetError = ReadGroupTransactionsGroupsGroupIdTransactionsGetErrors[keyof ReadGroupTransactionsGroupsGroupIdTransactionsGetErrors];

export type ReadGroupTransactionsGroupsGroupIdTransactionsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<TransactionRead>;
};

export type ReadGroupTransactionsGroupsGroupIdTransactionsGetResponse = ReadGroupTransactionsGroupsGroupIdTransactionsGetResponses[keyof ReadGroupTransactionsGroupsGroupIdTransactionsGetResponses];

export type DeleteUserFromGroupGroupsGroupIdUsersUserIdDeleteData = {
    body?: never;
    path: {
        group_id: string;
        user_id: string;
    };
    query?: never;
    url: '/groups/{group_id}/users/{user_id}';
};

export type DeleteUserFromGroupGroupsGroupIdUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserFromGroupGroupsGroupIdUsersUserIdDeleteError = DeleteUserFromGroupGroupsGroupIdUsersUserIdDeleteErrors[keyof DeleteUserFromGroupGroupsGroupIdUsersUserIdDeleteErrors];

export type DeleteUserFromGroupGroupsGroupIdUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: GroupExpandedResponse;
};

export type DeleteUserFromGroupGroupsGroupIdUsersUserIdDeleteResponse = DeleteUserFromGroupGroupsGroupIdUsersUserIdDeleteResponses[keyof DeleteUserFromGroupGroupsGroupIdUsersUserIdDeleteResponses];

export type GetMyInvitesInvitesMyInvitesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/invites/my-invites';
};

export type GetMyInvitesInvitesMyInvitesGetResponses = {
    /**
     * Successful Response
     */
    200: Array<GroupInviteResponse>;
};

export type GetMyInvitesInvitesMyInvitesGetResponse = GetMyInvitesInvitesMyInvitesGetResponses[keyof GetMyInvitesInvitesMyInvitesGetResponses];

export type GenerateInviteLinkInvitesGroupIdGeneratePostData = {
    body?: never;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/invites/{group_id}/generate';
};

export type GenerateInviteLinkInvitesGroupIdGeneratePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateInviteLinkInvitesGroupIdGeneratePostError = GenerateInviteLinkInvitesGroupIdGeneratePostErrors[keyof GenerateInviteLinkInvitesGroupIdGeneratePostErrors];

export type GenerateInviteLinkInvitesGroupIdGeneratePostResponses = {
    /**
     * Successful Response
     */
    201: InvitationTokenResponse;
};

export type GenerateInviteLinkInvitesGroupIdGeneratePostResponse = GenerateInviteLinkInvitesGroupIdGeneratePostResponses[keyof GenerateInviteLinkInvitesGroupIdGeneratePostResponses];

export type InviteByEmailInvitesGroupIdEmailPostData = {
    body: GroupInviteCreate;
    path: {
        group_id: string;
    };
    query?: never;
    url: '/invites/{group_id}/email';
};

export type InviteByEmailInvitesGroupIdEmailPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InviteByEmailInvitesGroupIdEmailPostError = InviteByEmailInvitesGroupIdEmailPostErrors[keyof InviteByEmailInvitesGroupIdEmailPostErrors];

export type InviteByEmailInvitesGroupIdEmailPostResponses = {
    /**
     * Successful Response
     */
    201: GroupInviteResponse;
};

export type InviteByEmailInvitesGroupIdEmailPostResponse = InviteByEmailInvitesGroupIdEmailPostResponses[keyof InviteByEmailInvitesGroupIdEmailPostResponses];

export type AcceptInviteInvitesAcceptTokenPutData = {
    body?: never;
    path: {
        token: string;
    };
    query?: never;
    url: '/invites/accept/{token}';
};

export type AcceptInviteInvitesAcceptTokenPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AcceptInviteInvitesAcceptTokenPutError = AcceptInviteInvitesAcceptTokenPutErrors[keyof AcceptInviteInvitesAcceptTokenPutErrors];

export type AcceptInviteInvitesAcceptTokenPutResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AcceptInviteInvitesAcceptTokenPutResponse = AcceptInviteInvitesAcceptTokenPutResponses[keyof AcceptInviteInvitesAcceptTokenPutResponses];

export type RejectInviteInvitesRejectTokenDeleteData = {
    body?: never;
    path: {
        token: string;
    };
    query?: never;
    url: '/invites/reject/{token}';
};

export type RejectInviteInvitesRejectTokenDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RejectInviteInvitesRejectTokenDeleteError = RejectInviteInvitesRejectTokenDeleteErrors[keyof RejectInviteInvitesRejectTokenDeleteErrors];

export type RejectInviteInvitesRejectTokenDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RejectInviteInvitesRejectTokenDeleteResponse = RejectInviteInvitesRejectTokenDeleteResponses[keyof RejectInviteInvitesRejectTokenDeleteResponses];

export type ReadTransactionsUserIsParticipantInTransactionsGetData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        limit?: number;
        group_id?: string | null;
    };
    url: '/transactions/';
};

export type ReadTransactionsUserIsParticipantInTransactionsGetErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTransactionsUserIsParticipantInTransactionsGetError = ReadTransactionsUserIsParticipantInTransactionsGetErrors[keyof ReadTransactionsUserIsParticipantInTransactionsGetErrors];

export type ReadTransactionsUserIsParticipantInTransactionsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<TransactionRead>;
};

export type ReadTransactionsUserIsParticipantInTransactionsGetResponse = ReadTransactionsUserIsParticipantInTransactionsGetResponses[keyof ReadTransactionsUserIsParticipantInTransactionsGetResponses];

export type CreateTransactionTransactionsPostData = {
    body: TransactionCreate;
    path?: never;
    query?: never;
    url: '/transactions/';
};

export type CreateTransactionTransactionsPostErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTransactionTransactionsPostError = CreateTransactionTransactionsPostErrors[keyof CreateTransactionTransactionsPostErrors];

export type CreateTransactionTransactionsPostResponses = {
    /**
     * Successful Response
     */
    201: TransactionRead;
};

export type CreateTransactionTransactionsPostResponse = CreateTransactionTransactionsPostResponses[keyof CreateTransactionTransactionsPostResponses];

export type DeleteTransactionTransactionsTransactionIdDeleteData = {
    body?: never;
    path: {
        transaction_id: string;
    };
    query?: never;
    url: '/transactions/{transaction_id}';
};

export type DeleteTransactionTransactionsTransactionIdDeleteErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTransactionTransactionsTransactionIdDeleteError = DeleteTransactionTransactionsTransactionIdDeleteErrors[keyof DeleteTransactionTransactionsTransactionIdDeleteErrors];

export type DeleteTransactionTransactionsTransactionIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTransactionTransactionsTransactionIdDeleteResponse = DeleteTransactionTransactionsTransactionIdDeleteResponses[keyof DeleteTransactionTransactionsTransactionIdDeleteResponses];

export type ReadTransactionTransactionsTransactionIdGetData = {
    body?: never;
    path: {
        transaction_id: string;
    };
    query?: never;
    url: '/transactions/{transaction_id}';
};

export type ReadTransactionTransactionsTransactionIdGetErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadTransactionTransactionsTransactionIdGetError = ReadTransactionTransactionsTransactionIdGetErrors[keyof ReadTransactionTransactionsTransactionIdGetErrors];

export type ReadTransactionTransactionsTransactionIdGetResponses = {
    /**
     * Successful Response
     */
    200: TransactionRead;
};

export type ReadTransactionTransactionsTransactionIdGetResponse = ReadTransactionTransactionsTransactionIdGetResponses[keyof ReadTransactionTransactionsTransactionIdGetResponses];

export type UpdateTransactionTransactionsTransactionIdPutData = {
    body: TransactionUpdate;
    path: {
        transaction_id: string;
    };
    query?: never;
    url: '/transactions/{transaction_id}';
};

export type UpdateTransactionTransactionsTransactionIdPutErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTransactionTransactionsTransactionIdPutError = UpdateTransactionTransactionsTransactionIdPutErrors[keyof UpdateTransactionTransactionsTransactionIdPutErrors];

export type UpdateTransactionTransactionsTransactionIdPutResponses = {
    /**
     * Successful Response
     */
    200: TransactionRead;
};

export type UpdateTransactionTransactionsTransactionIdPutResponse = UpdateTransactionTransactionsTransactionIdPutResponses[keyof UpdateTransactionTransactionsTransactionIdPutResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};