// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zBodyLoginAuthLoginPost = z.object({
    grant_type: z.union([
        z.string().regex(/^password$/),
        z.null()
    ]).optional(),
    username: z.string(),
    password: z.string(),
    scope: z.string().optional().default(''),
    client_id: z.union([
        z.string(),
        z.null()
    ]).optional(),
    client_secret: z.union([
        z.string(),
        z.null()
    ]).optional()
});

export const zCreateGroup = z.object({
    name: z.string().min(1).max(100)
});

export const zEmailConfirmationRequest = z.object({
    frontend_url: z.string().min(1).max(500),
    token: z.number().int()
});

export const zGroup = z.object({
    id: z.string().uuid().optional(),
    created_at: z.string().datetime().optional(),
    updated_at: z.string().datetime().optional(),
    name: z.string().min(1).max(100)
});

export const zGroupInviteCreate = z.object({
    email: z.union([
        z.string().email(),
        z.null()
    ]).optional()
});

export const zGroupInviteResponse = z.object({
    id: z.string().uuid(),
    email: z.union([
        z.string(),
        z.null()
    ]).optional(),
    group_id: z.string().uuid(),
    token: z.string(),
    created_at: z.string().datetime()
});

export const zGroupWithUsersResponse = z.object({
    id: z.string().uuid(),
    name: z.string(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime(),
    users: z.array(z.object({
        id: z.string().uuid(),
        email: z.string().email(),
        username: z.string(),
        email_verified: z.boolean(),
        created_at: z.string().datetime(),
        updated_at: z.string().datetime()
    })).optional().default([]),
    invites: z.union([
        z.array(zGroupInviteResponse),
        z.null()
    ]).optional()
});

export const zHttpValidationError = z.object({
    detail: z.array(z.object({
        loc: z.array(z.unknown()),
        msg: z.string(),
        type: z.string()
    })).optional()
});

export const zInvitationTokenResponse = z.object({
    token: z.string()
});

export const zToken = z.object({
    access_token: z.string(),
    token_type: z.string()
});

export const zTransactionCreate = z.object({
    id: z.string().uuid().optional(),
    created_at: z.string().datetime().optional(),
    updated_at: z.string().datetime().optional(),
    amount: z.number().int(),
    title: z.string(),
    purchased_on: z.string().datetime().optional(),
    transaction_type: z.enum([
        'EVEN',
        'AMOUNT',
        'PERCENTAGE'
    ]).optional(),
    group_id: z.string().uuid(),
    payer_id: z.string().uuid(),
    participants: z.array(z.object({
        amount_owed: z.number().int(),
        debtor_id: z.string().uuid()
    }))
});

export const zTransactionParticipantCreate = z.object({
    amount_owed: z.number().int(),
    debtor_id: z.string().uuid()
});

export const zTransactionParticipantRead = z.object({
    amount_owed: z.number().int(),
    transaction_id: z.string().uuid(),
    debtor_id: z.string().uuid(),
    id: z.string().uuid(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime(),
    debtor: z.object({
        id: z.string().uuid().optional(),
        created_at: z.string().datetime().optional(),
        updated_at: z.string().datetime().optional(),
        username: z.string().min(1).max(50),
        email: z.string().min(1).max(255),
        email_verified: z.boolean().optional().default(false),
        email_verification_token: z.number().int().optional(),
        password: z.string().min(8)
    })
});

export const zTransactionRead = z.object({
    id: z.string().uuid().optional(),
    created_at: z.string().datetime().optional(),
    updated_at: z.string().datetime().optional(),
    amount: z.number().int(),
    title: z.string(),
    purchased_on: z.string().datetime().optional(),
    transaction_type: z.enum([
        'EVEN',
        'AMOUNT',
        'PERCENTAGE'
    ]).optional(),
    group_id: z.string().uuid(),
    payer_id: z.string().uuid(),
    participants: z.array(zTransactionParticipantRead),
    payer: z.object({
        id: z.string().uuid().optional(),
        created_at: z.string().datetime().optional(),
        updated_at: z.string().datetime().optional(),
        username: z.string().min(1).max(50),
        email: z.string().min(1).max(255),
        email_verified: z.boolean().optional().default(false),
        email_verification_token: z.number().int().optional(),
        password: z.string().min(8)
    }),
    group: zGroup
});

export const zTransactionType = z.enum([
    'EVEN',
    'AMOUNT',
    'PERCENTAGE'
]);

export const zTransactionUpdate = z.object({
    amount: z.union([
        z.number().int(),
        z.null()
    ]).optional(),
    title: z.union([
        z.string(),
        z.null()
    ]).optional(),
    purchased_on: z.union([
        z.string().datetime(),
        z.null()
    ]).optional(),
    transaction_type: z.union([
        zTransactionType,
        z.null()
    ]).optional(),
    payer_id: z.union([
        z.string().uuid(),
        z.null()
    ]).optional()
});

export const zUpdateGroup = z.object({
    name: z.string().min(1).max(100).optional()
});

export const zUser = z.object({
    id: z.string().uuid().optional(),
    created_at: z.string().datetime().optional(),
    updated_at: z.string().datetime().optional(),
    username: z.string().min(1).max(50),
    email: z.string().min(1).max(255),
    email_verified: z.boolean().optional().default(false),
    email_verification_token: z.number().int().optional(),
    password: z.string().min(8)
});

export const zUserCreate = z.object({
    email: z.string().email(),
    password: z.string().min(8).max(32),
    username: z.string().min(1).max(50)
});

export const zUserInfoUpdate = z.object({
    username: z.string().min(1).max(50)
});

export const zUserResponse = z.object({
    id: z.string().uuid(),
    email: z.string().email(),
    username: z.string(),
    email_verified: z.boolean(),
    created_at: z.string().datetime(),
    updated_at: z.string().datetime()
});

export const zUserUpdatePassword = z.object({
    old_password: z.string().min(8),
    new_password: z.string().min(8).max(32)
});

export const zValidationError = z.object({
    loc: z.array(z.unknown()),
    msg: z.string(),
    type: z.string()
});

export const zDeleteUserAccountDeleteResponse = z.void();

export const zReadUsersMeAccountGetResponse = zUserResponse;

export const zUpdateUserInfoAccountPutResponse = z.object({});

export const zUpdatePasswordAccountPasswordPutResponse = z.object({});

export const zRegisterAuthRegisterPostResponse = zUserResponse;

export const zLoginAuthLoginPostResponse = zToken;

export const zConfirmEmailAuthConfirmEmailPostResponse = zToken;

export const zReadGroupsGroupsGetResponse = z.array(zGroup);

export const zCreateGroupGroupsPostResponse = zGroup;

export const zDeleteGroupGroupsGroupIdDeleteResponse = z.void();

export const zReadGroupGroupsGroupIdGetResponse = zGroupWithUsersResponse;

export const zUpdateGroupGroupsGroupIdPutResponse = zGroup;

export const zReadGroupTransactionsGroupsGroupIdTransactionsGetResponse = z.array(zTransactionRead);

export const zDeleteUserFromGroupGroupsGroupIdUsersUserIdDeleteResponse = zGroupWithUsersResponse;

export const zGetMyInvitesInvitesMyInvitesGetResponse = z.array(zGroupInviteResponse);

export const zGenerateInviteLinkInvitesGroupIdGeneratePostResponse = zInvitationTokenResponse;

export const zInviteByEmailInvitesGroupIdEmailPostResponse = zGroupInviteResponse;

export const zAcceptInviteInvitesAcceptTokenPutResponse = z.object({});

export const zRejectInviteInvitesRejectTokenDeleteResponse = z.void();

export const zReadTransactionsUserIsParticipantInTransactionsGetResponse = z.array(zTransactionRead);

export const zCreateTransactionTransactionsPostResponse = zTransactionRead;

export const zDeleteTransactionTransactionsTransactionIdDeleteResponse = z.void();

export const zReadTransactionTransactionsTransactionIdGetResponse = zTransactionRead;

export const zUpdateTransactionTransactionsTransactionIdPutResponse = zTransactionRead;